[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
account_voter = "GNATWpZAcWZZjrC5j774mw7NUpM3C9UQAcEVw6HiBmyW"

[programs.devnet]
account_voter = "GNATWpZAcWZZjrC5j774mw7NUpM3C9UQAcEVw6HiBmyW"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
