[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
account_voter = "6dPHkxoJGDyt4h37htgrm62zJU6aLdfHFcfX7KcHcyae"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nicolasvilla/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
