[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
account_voter = "9cdkzeKvJaA9evco79NmzG4sGuDSuAQokvgsV8WSk8N3"

[programs.localnet]
account_voter = "BpemDQtKwdVzWkT7pxyddsQf1boX9bS7sENHaxra2rrs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/debian/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
